# Generated by Django 5.0.7 on 2024-08-06 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesTest',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('rec_id', models.DateField(blank=True, null=True)),
                ('rec_type', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_fileTest',
            },
        ),
    ]
