# Generated by Django 4.2.7 on 2024-08-06 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_filestest'),
    ]

    operations = [
        migrations.CreateModel(
            name='password_storage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('passwordText', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_repos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_storage',
            },
        ),
    ]
