# Generated by Django 4.2.7 on 2024-08-06 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_password_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='error_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('error_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'error_log',
            },
        ),
    ]
