# Generated by Django 4.2.7 on 2024-08-06 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_error_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error_log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
