# Generated by Django 4.2.7 on 2024-08-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
