# Generated by Django 4.2.7 on 2024-09-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_customuser_device_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_role_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('role_id', models.BigIntegerField(blank=True, null=True)),
                ('company_id', models.BigIntegerField(blank=True, null=True)),
                ('worksite', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_role_mapping',
            },
        ),
    ]
