# Generated by Django 4.2.7 on 2024-09-06 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_rename_user_role_mapping_user_role_map_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMenuDetails',
            fields=[
                ('user_menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_id', models.IntegerField(blank=True, null=True)),
                ('role_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_menu_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_menu_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_menu_details',
            },
        ),
        migrations.CreateModel(
            name='RoleMenuMaster',
            fields=[
                ('role_menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_id', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_menu_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_menu_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'role_menu_master',
            },
        ),
        migrations.CreateModel(
            name='MenuMaster',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_action', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_is_parent', models.BooleanField(blank=True, null=True)),
                ('menu_parent_id', models.IntegerField(blank=True, null=True)),
                ('menu_order', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('is_sub_menu', models.BooleanField(blank=True, null=True)),
                ('sub_menu', models.IntegerField(blank=True, null=True)),
                ('is_sub_menu2', models.BooleanField(blank=True, null=True)),
                ('sub_menu2', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('menu_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menu_master',
            },
        ),
    ]
