# Generated by Django 4.2.7 on 2024-08-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_roles'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roles',
            table='roles',
        ),
    ]
