# Generated by Django 4.2.7 on 2024-09-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_usermenudetails_rolemenumaster_menumaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumaster',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menumaster',
            name='updated_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rolemenumaster',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rolemenumaster',
            name='updated_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermenudetails',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermenudetails',
            name='updated_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
