# Generated by Django 4.2.7 on 2024-09-17 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_alter_menumaster_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password_storage',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_repos', to=settings.AUTH_USER_MODEL),
        ),
    ]
