# Generated by Django 4.2.7 on 2024-08-22 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_alter_roles_created_by_alter_roles_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roles',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
