# Generated by Django 4.2.7 on 2024-08-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_alter_roles_created_by_alter_roles_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='encrypted_password',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password_text',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='title',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
