# Generated by Django 4.2.7 on 2024-09-03 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Masters', '0011_sc_roster_confirmation_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='notification_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_sent', models.DateTimeField(blank=True, null=True)),
                ('notification_received', models.DateTimeField(blank=True, null=True)),
                ('notification_opened', models.DateTimeField(blank=True, null=True)),
                ('notification_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_created_by', to=settings.AUTH_USER_MODEL)),
                ('sc_roster_id', models.ForeignKey(blank=True, db_column='sc_roster_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sc_roster_id', to='Masters.sc_roster')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_log',
            },
        ),
    ]
