# Generated by Django 4.2.7 on 2024-11-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0003_alter_notification_log_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'test_table',
            },
        ),
    ]
