# Generated by Django 5.0.7 on 2024-08-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Conractor',
        ),
        migrations.DeleteModel(
            name='ContractorRegData',
        ),
        migrations.DeleteModel(
            name='DatContRegSmpL',
        ),
        migrations.DeleteModel(
            name='Government',
        ),
        migrations.DeleteModel(
            name='LicenseType',
        ),
        migrations.DeleteModel(
            name='LicenseTypeL',
        ),
        migrations.DeleteModel(
            name='location',
        ),
        migrations.DeleteModel(
            name='locationdropdownspecial',
        ),
        migrations.DeleteModel(
            name='LocationLicense',
        ),
        migrations.DeleteModel(
            name='LocationTemplateMapping',
        ),
        migrations.DeleteModel(
            name='LocationUploadN',
        ),
        migrations.DeleteModel(
            name='Privilege',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.DeleteModel(
            name='UnitEdit',
        ),
        migrations.DeleteModel(
            name='UserCompanyLocation',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
        migrations.DeleteModel(
            name='UserPrivilege',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
