# Generated by Django 4.2.7 on 2024-08-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
