# Generated by Django 4.2.7 on 2024-08-06 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Masters', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site_master',
            old_name='company_id',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='sc_employee_master',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sc_employee_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sc_employee_master',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sc_employee_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sc_roaster',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='site_master',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='site_master',
            name='roster_type',
            field=models.ForeignKey(blank=True, db_column='roster_type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_relation', to='Masters.parameter_master'),
        ),
        migrations.AlterField(
            model_name='site_master',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
