# Generated by Django 4.2.7 on 2024-08-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0003_delete_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sc_roster',
            old_name='site',
            new_name='employee_name',
        ),
        migrations.AddField(
            model_name='sc_roster',
            name='worksite',
            field=models.TextField(blank=True, null=True),
        ),
    ]
