# Generated by Django 4.2.7 on 2024-08-26 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0004_rename_site_sc_roster_employee_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sc_employee_master',
            old_name='current_location',
            new_name='worksite',
        ),
    ]
