# Generated by Django 4.2.7 on 2024-08-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0008_remove_file_checksum_uploaded_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_errorlog',
            name='status',
        ),
    ]
