# Generated by Django 4.2.7 on 2024-09-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0011_sc_roster_confirmation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
