# Generated by Django 4.2.7 on 2024-08-20 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Masters', '0013_sc_employee_master_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sc_roaster',
            new_name='sc_roster',
        ),
        migrations.RemoveField(
            model_name='sc_employee_master',
            name='employee_status',
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='employment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_data', to='Masters.parameter_master'),
        ),
    ]
