# Generated by Django 4.2.7 on 2024-09-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0013_rename_attendance_sc_roster_attendance_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc_roster',
            name='attendance_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
