# Generated by Django 4.2.7 on 2024-08-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0014_rename_sc_roaster_sc_roster_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sc_roster',
            table='sc_roster',
        ),
    ]
