# Generated by Django 4.2.7 on 2024-08-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0015_alter_sc_roster_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc_roster',
            name='attendance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sc_roster',
            name='confirmation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sc_roster',
            name='shift_from',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sc_roster',
            name='shift_to',
            field=models.TextField(blank=True, null=True),
        ),
    ]
