# Generated by Django 4.2.7 on 2024-08-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0016_sc_roster_attendance_sc_roster_confirmation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sc_roster',
            old_name='shift_from',
            new_name='shift_time',
        ),
        migrations.RemoveField(
            model_name='sc_roster',
            name='shift_to',
        ),
    ]
