# Generated by Django 4.2.7 on 2024-08-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0017_rename_shift_from_sc_roster_shift_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc_roster',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='Masters.company_master'),
        ),
        migrations.AlterField(
            model_name='sc_roster',
            name='site',
            field=models.TextField(blank=True, null=True),
        ),
    ]
