# Generated by Django 4.2.7 on 2024-09-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0017_alter_company_master_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_search',
            name='menu_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application_search',
            name='user_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
