# Generated by Django 4.2.7 on 2024-08-23 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Masters', '0018_sc_roster_company_alter_sc_roster_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_checksum',
            fields=[
                ('checksum_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_for', models.TextField(blank=True, null=True)),
                ('site', models.TextField(blank=True, null=True)),
                ('month', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('checksum_description', models.TextField(blank=True, null=True)),
                ('uploaded_date', models.DateTimeField(blank=True, null=True)),
                ('operation_type', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('error_count', models.TextField(blank=True, null=True)),
                ('update_count', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checksum_company', to='Masters.company_master')),
            ],
            options={
                'db_table': 'file_checksum',
            },
        ),
        migrations.AlterField(
            model_name='sc_roster',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roster_company', to='Masters.company_master'),
        ),
        migrations.AlterField(
            model_name='sc_roster',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roster_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sc_roster',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roster_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='file_errorlog',
            fields=[
                ('error_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_for', models.TextField(blank=True, null=True)),
                ('site', models.TextField(blank=True, null=True)),
                ('month', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('error_description', models.TextField(blank=True, null=True)),
                ('uploaded_date', models.DateTimeField(blank=True, null=True)),
                ('operation_type', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('checksum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checksum1_created_by', to='Masters.file_checksum')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errorlog_company', to='Masters.company_master')),
            ],
            options={
                'db_table': 'file_errorlog',
            },
        ),
    ]
