# Generated by Django 4.2.7 on 2024-08-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0019_file_checksum_alter_sc_roster_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_checksum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='file_checksum',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
