# Generated by Django 4.2.7 on 2024-11-12 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0019_remove_application_search_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc_employee_master',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_company_relation', to='Masters.company_master'),
        ),
    ]
