# Generated by Django 4.2.7 on 2024-11-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0020_sc_employee_master_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sc_employee_master',
            old_name='company',
            new_name='company_id',
        ),
    ]
