# Generated by Django 4.2.7 on 2024-08-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0020_file_checksum_created_at_file_checksum_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_errorlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='file_errorlog',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
