# Generated by Django 4.2.7 on 2024-08-23 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Masters', '0021_file_errorlog_created_at_file_errorlog_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_checksum',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checksum_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file_checksum',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checksum_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
