# Generated by Django 4.2.7 on 2024-11-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0022_remove_sc_employee_master_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sc_roster',
            name='attendance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
