# Generated by Django 4.2.7 on 2024-11-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0023_alter_sc_roster_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sc_employee_master',
            name='company',
        ),
    ]
