# Generated by Django 4.2.7 on 2024-11-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0024_alter_sc_roster_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sc_roster',
            old_name='attendance_date',
            new_name='attendance_uploaded_date',
        ),
    ]
