# Generated by Django 4.2.7 on 2024-11-26 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0024_remove_sc_employee_master_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc_employee_master',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_employee_relation', to='Masters.company_master'),
        ),
    ]
