# Generated by Django 4.2.7 on 2024-12-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0025_rename_attendance_date_sc_roster_attendance_uploaded_date'),
        ('Masters', '0025_sc_employee_master_company'),
    ]

    operations = [
    ]
