# Generated by Django 4.2.7 on 2024-09-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report_columns',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity', models.TextField(blank=True, null=True)),
                ('field_name', models.TextField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('join_name', models.TextField(blank=True, null=True)),
                ('join_clause', models.TextField(blank=True, null=True)),
                ('order', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_columns',
            },
        ),
        migrations.CreateModel(
            name='report_filters',
            fields=[
                ('filter_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity', models.TextField(blank=True, null=True)),
                ('filter_parameter', models.TextField(blank=True, null=True)),
                ('filter_values', models.TextField(blank=True, null=True)),
                ('from_clause', models.TextField(blank=True, null=True)),
                ('where_clause', models.TextField(blank=True, null=True)),
                ('join_clause', models.TextField(blank=True, null=True)),
                ('group_by', models.TextField(blank=True, null=True)),
                ('order_by', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_mandatory', models.TextField(blank=True, null=True)),
                ('order', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_filters',
            },
        ),
        migrations.CreateModel(
            name='saved_report_filters',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('saved_name', models.TextField(blank=True, null=True)),
                ('entity', models.TextField(blank=True, null=True)),
                ('filters', models.TextField(blank=True, null=True)),
                ('sub_filters', models.TextField(blank=True, null=True)),
                ('selected_columns', models.TextField(blank=True, null=True)),
                ('filter_count', models.TextField(blank=True, null=True)),
                ('display_names', models.TextField(blank=True, null=True)),
                ('sql_query', models.TextField(blank=True, null=True)),
                ('user_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'saved_report_filters',
            },
        ),
    ]
